package legend.game.combat.ui;

public enum FooterActionColor {
  FOOTER_BROWN,
  FOOTER_WHITE,
  FOOTER_GREY,
  FOOTER_RED,
  FOOTER_PINK,
  FOOTER_PURPLE,
  FOOTER_BLUE,
  FOOTER_AQUA,
  FOOTER_GREEN,
  FOOTER_LIME,
  FOOTER_YELLOW,
  FOOTER_ORANGE
}
